### ISSUE TITLE
请求提供全部源码

### ISSUE THREAD

**Issue by BKcurrant** [wotchin/SmooFaceEngine#10]
书里的代码全部自己打效率太低了

**Comment by wotchin** [comment]
你好，现在我这里也没有各章节代码，等后面有时间我尝试更新一下。谢谢。

**Comment by Suimingzhe** [comment]
一样，求源代码，这样看书方便很多，谢谢

**Comment by lwdred** [comment]
这本书，说是实践，结果到了最后竟然没讲解，一带而过，这是太失望了，真是本失败的入门书

**Comment by wotchin** [comment]
感谢反馈，已补充部分内容，后续会持续跟进，谢谢。
