### ISSUE TITLE
你好，请指定版本，目前很多库都升级了，导致代码无法运行

### ISSUE THREAD

**Issue by xavieryang007** [wotchin/SmooFaceEngine#12]
TensorFlow等都升级了，尤其TensorFlow都2.0了，很多接口有调整，导致项目无法运行，希望可以给用到的所有库都指定一下版本号。多谢

**Comment by wotchin** [comment]
好的，请稍等，随后我会更新在requirements.txt 文件中

**Comment by wotchin** [comment]
你好，请尝试:
tensorflow 1.14
Keras 2.1.2
scipy 1.3.1
scikit-learn 0.21.3
