### ISSUE TITLE
P141 2处代码有误。

### ISSUE THREAD

**Issue by AIWeiJT** [wotchin/SmooFaceEngine#15]
1.代码清单5-5 代码有误：model.layers[output_layer] 应为 model.layers[output_layer_index]
2.本页下面。载入模型文件时，调用函数 get_feature_function()时，参数应为 output_layer_index=7

**Comment by wotchin** [comment]
感谢勘误！
已修改：
https://github.com/wotchin/SmooFaceEngine/wiki/errata
