### ISSUE TITLE
书上第26页最下面那个公式

### ISSUE THREAD

**Issue by chaotianjiao** [wotchin/SmooFaceEngine#16]
![Snipaste_2020-02-19_09-30-01](https://user-images.githubusercontent.com/42534375/74793431-453b3b00-52fb-11ea-83ae-1473696ef3a0.jpg)
是应该这样吗，还是我理解错了？

**Comment by wotchin** [comment]
您好，这里应该应该是 -1, 是书中写错了，我会在勘误表中更新，感谢反馈。
