### ISSUE TITLE
82页代码清单4-15，出来的图片与图4-8不符

### ISSUE THREAD

**Issue by G-Apple1** [wotchin/SmooFaceEngine#17]
82页代码清单4-15，
运行出来的图片与图4-8不符

**Comment by chaotianjiao** [comment]
4-15代码清单
最后一行应该是cv2.imwrite('dst.jpg',rotated_img)
另外我出来的效果是这样的，
![image](https://user-images.githubusercontent.com/42534375/77894404-d1039800-72a7-11ea-816a-00d7ec245a15.png)
我的image.shape是（512，512，3）

**Comment by wotchin** [comment]
感谢 @chaotianjiao  的bugfix. 代码最后一行应当输出 rotated_img.
输出的图片差异较大，应该是原始图片不同导致的。可以尝试使用书中原图，图片地址：
https://github.com/wotchin/SmooFaceEngine/blob/master/chapter-code/figures/lena.jpg
