### ISSUE TITLE
ImportError: No module named 'utils'

### ISSUE THREAD

**Issue by wangsai0806** [wotchin/SmooFaceEngine#18]
>python train.py
Using TensorFlow backend.
2020-04-17 20:47:49.333821: W tensorflow/stream_executor/platform/default/dso_lo
ader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64
_101.dll not found
2020-04-17 20:47:49.343821: I tensorflow/stream_executor/cuda/cudart_stub.cc:29]
 Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "train.py", line 6, in <module>
    from utils.data_generator import DataGenerator
ImportError: No module named 'utils'

执行源码报这个错，请问一下什么原因导致的？谢谢

**Comment by wangsai0806** [comment]
Package              Version     
-------------------- ------------
absl-py              0.9.0       
astor                0.8.1       
cachetools           4.1.0       
certifi              2018.8.24   
chardet              3.0.4       
cheroot              8.3.0       
click                7.1.1       
cycler               0.10.0      
Flask                1.1.2       
gast                 0.2.2       
google-auth          1.14.0      
google-auth-oauthlib 0.4.1       
google-pasta         0.2.0       
grpcio               1.28.1      
h5py                 2.10.0      
idna                 2.9         
itsdangerous         1.1.0       
jaraco.functools     2.0         
Jinja2               2.11.2      
joblib               0.14.1      
Keras                2.3.1       
Keras-Applications   1.0.8       
Keras-Preprocessing  1.1.0       
kiwisolver           1.1.0       
Markdown             3.2.1       
MarkupSafe           1.1.1       
matplotlib           3.0.3       
mkl-fft              1.0.6       
mkl-random           1.0.1       
more-itertools       8.2.0       
numpy                1.18.2      
oauthlib             3.1.0       
opencv-python        4.2.0.34    
opt-einsum           3.2.1       
pip                  20.0.2      
protobuf             3.11.3      
pyasn1               0.4.8       
pyasn1-modules       0.2.8       
pyparsing            2.4.7       
python-dateutil      2.8.1       
PyYAML               5.3.1       
requests             2.23.0      
requests-oauthlib    1.3.0       
rsa                  4.0         
scikit-learn         0.22.2.post1
scipy                1.4.1       
setuptools           46.1.3      
six                  1.14.0      
sklearn              0.0         
TBB                  0.1         
tensorboard          2.1.1       
tensorflow           2.1.0       
tensorflow-estimator 2.1.0       
termcolor            1.1.0       
urllib3              1.25.9      
web.py               0.40.dev1   
Werkzeug             1.0.1       
wheel                0.31.1      
wincertstore         0.2         
wrapt                1.12.1

**Comment by wotchin** [comment]
当前执行的路径不正确，可以在项目根目录中运行。
或者指定PYTHONPATH, 
如在项目根目录中执行下列shell语句：
export PYTHONPATH=`pwd`:$PYTHONPATH.
上述针对Linux， 在Windows上调试的话，IDE有执行根目录选项，如PyCharm的 右键选中根目录，Mark directory as -> Source Root, 这样默认情况下run 时，会把环境变量加入进去。
