### ISSUE TITLE
勘误

### ISSUE THREAD

**Issue by xmLi0501** [wotchin/SmooFaceEngine#19]
依据P82的图像旋转代码，编译后图像显示很小很小，几乎看不到，所以添加了cv2.warpAffine(）函数后就可以正常实现旋转

**Comment by wotchin** [comment]
Excellent! 
可以尝试使用一下项目原始图片：https://github.com/wotchin/SmooFaceEngine/tree/master/chapter-code/figures
如果代码需要修正的话，请发一个PR过来，谢谢。
