### ISSUE TITLE
运行train.py报ValueError: No gradients provided for any variable错误

### ISSUE THREAD

**Issue by mixml** [wotchin/SmooFaceEngine#20]
操作系统：win10 64位
TensorFlow版本：2.3.0
CUDA10.1
运行train.py时报错：
ValueError: No gradients provided for any variable: ['conv1/kernel:0', 'conv1/bias:0', 'batch_normalization/gamma:0', 'batch_normalization/beta:0', 'conv2d/kernel:0', 'conv2d/bias:0', 'batch_normalization_1/gamma:0', 'batch_normalization_1/beta:0', 'conv2d_1/kernel:0', 'conv2d_1/bias:0', 'conv2d_2/kernel:0', 'conv2d_2/bias:0', 'batch_normalization_2/gamma:0', 'batch_normalization_2/beta:0', 'batch_normalization_3/gamma:0', 'batch_normalization_3/beta:0', 'conv2d_3/kernel:0', 'conv2d_3/bias:0', 'batch_normalization_4/gamma:0', 'batch_normalization_4/beta:0', 'conv2d_4/kernel:0', 'conv2d_4/bias:0', 'batch_normalization_5/gamma:0', 'batch_normalization_5/beta:0', 'conv2d_5/kernel:0', 'conv2dbatch_normalization_14/gamma:0', 'batch_normalization_14/beta:0', 'conv2d_14/kernel:0', 'conv2d_14/bias:0', 'batch_normalization_15/gamma:0', 'batch_normalization_15/beta:0', 'conv2d_15/kernel:0', 'conv2d_15/bias:0', 'batch_normalization_16/gah_normalization_17/gamma:0', 'batc_5/bias:mma:0', 'batch_normalization_16/beta:0', 'conv2d_16/kernel:0', 'conv2d_16/bias:0', 'conv2d_17/kernel:0', 'conv2d_17/bias:0', 'batc0', 'batch_normalization_6/gamma:0', 'batch_normalization_6/beta:0', 'conv2d_6/kernel:0', 'conv2d_6/bias:0', 'conv2d_7/kernel:0', 'conv2d_7/bias:0', 'batch_normalization_7/gamma:0', 'batch_normalization_7/beta:0', 'batch_normalization_8/gamma:0', 'batch_normalization_8/beta:0', 'conv2d_8/kernel:0', 'conv2d_8/bias:0', 'batch_normalization_9/gamma:0', 'batch_normalization_9/beta:0', 'conv2d_9/kernel:0', 'conv2d_9/bias:0', 'batch_normalization_10/gamma:0', 'batch_normalization_10/beta:0', 'conv2d_10/kernel:0', 'conv2d_10/bias:0', 'batch_normalization_11/gamma:0', 'batch_normalization_11/beta:0', 'conv2d_11/kernel:0', 'conv2d_11/bias:0', 'conv2d_12/kernel:0', 'conv2d_12/bias:0', 'batch_normalization_12/gamma:0', 'batch_normalization_12/beta:0', 'batch_normalization_13/gamma:0', 'batch_normalization_13/beta:0', 'conv2d_13/kernel:0', 'conv2d_13/bias:0', 'h_normalization_17/beta:0', 'batch_normalization_18/gamma:0', 'batch_normalization_18/beta:0', 'conv2d_18/kernel:0', 'conv2d_18/bias:0', 'batch_normalization_19/gamma:0', 'batch_normalization_19/beta:0', 'conv2d_19/kernel:0', 'conv2d_19/bias:0', 'batch_normalization_20/gamma:0', 'batch_normalization_20/beta:0', 'predictions/kernel:0']

**Comment by wotchin** [comment]
有没有详细的错误栈？
可以尝试确认版本是否是如下版本：

flask 1.1.1
h5py 2.10.0
Keras 2.3.1
numpy 1.17.1
scipy 1.3.2
tensorflow 1.14.0

**Comment by mixml** [comment]
详细的错误栈如下：

In[2]: runfile('F:/6_Source-code/SmooFaceEngine/train.py', wdir='F:/6_Source-code/SmooFaceEngine')
2020-10-20 15:56:17.603194: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
40 8400 6720 1680
2020-10-20 15:56:53.699667: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library nvcuda.dll
2020-10-20 15:56:53.753165: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GTX 1060 computeCapability: 6.1
coreClock: 1.6705GHz coreCount: 10 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 178.99GiB/s
2020-10-20 15:56:53.753923: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
2020-10-20 15:56:53.816207: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cublas64_10.dll
2020-10-20 15:56:53.850198: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cufft64_10.dll
2020-10-20 15:56:53.877634: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library curand64_10.dll
2020-10-20 15:56:53.916899: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusolver64_10.dll
2020-10-20 15:56:53.935859: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusparse64_10.dll
2020-10-20 15:56:54.003804: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudnn64_7.dll
2020-10-20 15:56:54.004677: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-10-20 15:56:54.019556: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-10-20 15:56:54.119519: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x201eb4dc490 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-10-20 15:56:54.120165: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-10-20 15:56:54.122499: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GTX 1060 computeCapability: 6.1
coreClock: 1.6705GHz coreCount: 10 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 178.99GiB/s
2020-10-20 15:56:54.123543: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
2020-10-20 15:56:54.124052: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cublas64_10.dll
2020-10-20 15:56:54.124602: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cufft64_10.dll
2020-10-20 15:56:54.125085: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library curand64_10.dll
2020-10-20 15:56:54.125680: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusolver64_10.dll
2020-10-20 15:56:54.126204: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusparse64_10.dll
2020-10-20 15:56:54.126878: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudnn64_7.dll
2020-10-20 15:56:54.127540: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-10-20 15:56:55.441100: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-20 15:56:55.441551: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0 
2020-10-20 15:56:55.441751: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N 
2020-10-20 15:56:55.443437: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4695 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060, pci bus id: 0000:01:00.0, compute capability: 6.1)
2020-10-20 15:56:55.450496: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x201910fbab0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-10-20 15:56:55.451094: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce GTX 1060, Compute Capability 6.1
Model: "functional_3"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input (InputLayer)              [(None, 64, 64, 1)]  0                                            
__________________________________________________________________________________________________
conv1_pad (ZeroPadding2D)       (None, 70, 70, 1)    0           input[0][0]                      
__________________________________________________________________________________________________
conv1 (Conv2D)                  (None, 32, 32, 64)   3200        conv1_pad[0][0]                  
__________________________________________________________________________________________________
batch_normalization (BatchNorma (None, 32, 32, 64)   256         conv1[0][0]                      
__________________________________________________________________________________________________
activation (Activation)         (None, 32, 32, 64)   0           batch_normalization[0][0]        
__________________________________________________________________________________________________
pool1_pad (ZeroPadding2D)       (None, 34, 34, 64)   0           activation[0][0]                 
__________________________________________________________________________________________________
max_pooling2d (MaxPooling2D)    (None, 16, 16, 64)   0           pool1_pad[0][0]                  
__________________________________________________________________________________________________
zero_padding2d (ZeroPadding2D)  (None, 18, 18, 64)   0           max_pooling2d[0][0]              
__________________________________________________________________________________________________
conv2d (Conv2D)                 (None, 8, 8, 64)     36928       zero_padding2d[0][0]             
__________________________________________________________________________________________________
batch_normalization_1 (BatchNor (None, 8, 8, 64)     256         conv2d[0][0]                     
__________________________________________________________________________________________________
activation_1 (Activation)       (None, 8, 8, 64)     0           batch_normalization_1[0][0]      
__________________________________________________________________________________________________
zero_padding2d_1 (ZeroPadding2D (None, 10, 10, 64)   0           activation_1[0][0]               
__________________________________________________________________________________________________
conv2d_1 (Conv2D)               (None, 8, 8, 64)     36928       zero_padding2d_1[0][0]           
__________________________________________________________________________________________________
conv2d_2 (Conv2D)               (None, 8, 8, 64)     4160        max_pooling2d[0][0]              
__________________________________________________________________________________________________
batch_normalization_2 (BatchNor (None, 8, 8, 64)     256         conv2d_1[0][0]                   
__________________________________________________________________________________________________
batch_normalization_3 (BatchNor (None, 8, 8, 64)     256         conv2d_2[0][0]                   
__________________________________________________________________________________________________
add (Add)                       (None, 8, 8, 64)     0           batch_normalization_2[0][0]      
                                                                 batch_normalization_3[0][0]      
__________________________________________________________________________________________________
activation_2 (Activation)       (None, 8, 8, 64)     0           add[0][0]                        
__________________________________________________________________________________________________
zero_padding2d_2 (ZeroPadding2D (None, 10, 10, 64)   0           activation_2[0][0]               
__________________________________________________________________________________________________
conv2d_3 (Conv2D)               (None, 8, 8, 64)     36928       zero_padding2d_2[0][0]           
__________________________________________________________________________________________________
batch_normalization_4 (BatchNor (None, 8, 8, 64)     256         conv2d_3[0][0]                   
__________________________________________________________________________________________________
activation_3 (Activation)       (None, 8, 8, 64)     0           batch_normalization_4[0][0]      
__________________________________________________________________________________________________
zero_padding2d_3 (ZeroPadding2D (None, 10, 10, 64)   0           activation_3[0][0]               
__________________________________________________________________________________________________
conv2d_4 (Conv2D)               (None, 8, 8, 64)     36928       zero_padding2d_3[0][0]           
__________________________________________________________________________________________________
batch_normalization_5 (BatchNor (None, 8, 8, 64)     256         conv2d_4[0][0]                   
__________________________________________________________________________________________________
add_1 (Add)                     (None, 8, 8, 64)     0           batch_normalization_5[0][0]      
                                                                 activation_2[0][0]               
__________________________________________________________________________________________________
activation_4 (Activation)       (None, 8, 8, 64)     0           add_1[0][0]                      
__________________________________________________________________________________________________
zero_padding2d_4 (ZeroPadding2D (None, 10, 10, 64)   0           activation_4[0][0]               
__________________________________________________________________________________________________
conv2d_5 (Conv2D)               (None, 4, 4, 128)    73856       zero_padding2d_4[0][0]           
__________________________________________________________________________________________________
batch_normalization_6 (BatchNor (None, 4, 4, 128)    512         conv2d_5[0][0]                   
__________________________________________________________________________________________________
activation_5 (Activation)       (None, 4, 4, 128)    0           batch_normalization_6[0][0]      
__________________________________________________________________________________________________
zero_padding2d_5 (ZeroPadding2D (None, 6, 6, 128)    0           activation_5[0][0]               
__________________________________________________________________________________________________
conv2d_6 (Conv2D)               (None, 4, 4, 128)    147584      zero_padding2d_5[0][0]           
__________________________________________________________________________________________________
conv2d_7 (Conv2D)               (None, 4, 4, 128)    8320        activation_4[0][0]               
__________________________________________________________________________________________________
batch_normalization_7 (BatchNor (None, 4, 4, 128)    512         conv2d_6[0][0]                   
__________________________________________________________________________________________________
batch_normalization_8 (BatchNor (None, 4, 4, 128)    512         conv2d_7[0][0]                   
__________________________________________________________________________________________________
add_2 (Add)                     (None, 4, 4, 128)    0           batch_normalization_7[0][0]      
                                                                 batch_normalization_8[0][0]      
__________________________________________________________________________________________________
activation_6 (Activation)       (None, 4, 4, 128)    0           add_2[0][0]                      
__________________________________________________________________________________________________
zero_padding2d_6 (ZeroPadding2D (None, 6, 6, 128)    0           activation_6[0][0]               
__________________________________________________________________________________________________
conv2d_8 (Conv2D)               (None, 4, 4, 128)    147584      zero_padding2d_6[0][0]           
__________________________________________________________________________________________________
batch_normalization_9 (BatchNor (None, 4, 4, 128)    512         conv2d_8[0][0]                   
__________________________________________________________________________________________________
activation_7 (Activation)       (None, 4, 4, 128)    0           batch_normalization_9[0][0]      
__________________________________________________________________________________________________
zero_padding2d_7 (ZeroPadding2D (None, 6, 6, 128)    0           activation_7[0][0]               
__________________________________________________________________________________________________
conv2d_9 (Conv2D)               (None, 4, 4, 128)    147584      zero_padding2d_7[0][0]           
__________________________________________________________________________________________________
batch_normalization_10 (BatchNo (None, 4, 4, 128)    512         conv2d_9[0][0]                   
__________________________________________________________________________________________________
add_3 (Add)                     (None, 4, 4, 128)    0           batch_normalization_10[0][0]     
                                                                 activation_6[0][0]               
__________________________________________________________________________________________________
activation_8 (Activation)       (None, 4, 4, 128)    0           add_3[0][0]                      
__________________________________________________________________________________________________
zero_padding2d_8 (ZeroPadding2D (None, 6, 6, 128)    0           activation_8[0][0]               
__________________________________________________________________________________________________
conv2d_10 (Conv2D)              (None, 2, 2, 256)    295168      zero_padding2d_8[0][0]           
__________________________________________________________________________________________________
batch_normalization_11 (BatchNo (None, 2, 2, 256)    1024        conv2d_10[0][0]                  
__________________________________________________________________________________________________
activation_9 (Activation)       (None, 2, 2, 256)    0           batch_normalization_11[0][0]     
__________________________________________________________________________________________________
zero_padding2d_9 (ZeroPadding2D (None, 4, 4, 256)    0           activation_9[0][0]               
__________________________________________________________________________________________________
conv2d_11 (Conv2D)              (None, 2, 2, 256)    590080      zero_padding2d_9[0][0]           
__________________________________________________________________________________________________
conv2d_12 (Conv2D)              (None, 2, 2, 256)    33024       activation_8[0][0]               
__________________________________________________________________________________________________
batch_normalization_12 (BatchNo (None, 2, 2, 256)    1024        conv2d_11[0][0]                  
__________________________________________________________________________________________________
batch_normalization_13 (BatchNo (None, 2, 2, 256)    1024        conv2d_12[0][0]                  
__________________________________________________________________________________________________
add_4 (Add)                     (None, 2, 2, 256)    0           batch_normalization_12[0][0]     
                                                                 batch_normalization_13[0][0]     
__________________________________________________________________________________________________
activation_10 (Activation)      (None, 2, 2, 256)    0           add_4[0][0]                      
__________________________________________________________________________________________________
zero_padding2d_10 (ZeroPadding2 (None, 4, 4, 256)    0           activation_10[0][0]              
__________________________________________________________________________________________________
conv2d_13 (Conv2D)              (None, 2, 2, 256)    590080      zero_padding2d_10[0][0]          
__________________________________________________________________________________________________
batch_normalization_14 (BatchNo (None, 2, 2, 256)    1024        conv2d_13[0][0]                  
__________________________________________________________________________________________________
activation_11 (Activation)      (None, 2, 2, 256)    0           batch_normalization_14[0][0]     
__________________________________________________________________________________________________
zero_padding2d_11 (ZeroPadding2 (None, 4, 4, 256)    0           activation_11[0][0]              
__________________________________________________________________________________________________
conv2d_14 (Conv2D)              (None, 2, 2, 256)    590080      zero_padding2d_11[0][0]          
__________________________________________________________________________________________________
batch_normalization_15 (BatchNo (None, 2, 2, 256)    1024        conv2d_14[0][0]                  
__________________________________________________________________________________________________
add_5 (Add)                     (None, 2, 2, 256)    0           batch_normalization_15[0][0]     
                                                                 activation_10[0][0]              
__________________________________________________________________________________________________
activation_12 (Activation)      (None, 2, 2, 256)    0           add_5[0][0]                      
__________________________________________________________________________________________________
zero_padding2d_12 (ZeroPadding2 (None, 4, 4, 256)    0           activation_12[0][0]              
__________________________________________________________________________________________________
conv2d_15 (Conv2D)              (None, 1, 1, 512)    1180160     zero_padding2d_12[0][0]          
__________________________________________________________________________________________________
batch_normalization_16 (BatchNo (None, 1, 1, 512)    2048        conv2d_15[0][0]                  
__________________________________________________________________________________________________
activation_13 (Activation)      (None, 1, 1, 512)    0           batch_normalization_16[0][0]     
__________________________________________________________________________________________________
zero_padding2d_13 (ZeroPadding2 (None, 3, 3, 512)    0           activation_13[0][0]              
__________________________________________________________________________________________________
conv2d_16 (Conv2D)              (None, 1, 1, 512)    2359808     zero_padding2d_13[0][0]          
__________________________________________________________________________________________________
conv2d_17 (Conv2D)              (None, 1, 1, 512)    131584      activation_12[0][0]              
__________________________________________________________________________________________________
batch_normalization_17 (BatchNo (None, 1, 1, 512)    2048        conv2d_16[0][0]                  
__________________________________________________________________________________________________
batch_normalization_18 (BatchNo (None, 1, 1, 512)    2048        conv2d_17[0][0]                  
__________________________________________________________________________________________________
add_6 (Add)                     (None, 1, 1, 512)    0           batch_normalization_17[0][0]     
                                                                 batch_normalization_18[0][0]     
__________________________________________________________________________________________________
activation_14 (Activation)      (None, 1, 1, 512)    0           add_6[0][0]                      
__________________________________________________________________________________________________
zero_padding2d_14 (ZeroPadding2 (None, 3, 3, 512)    0           activation_14[0][0]              
__________________________________________________________________________________________________
conv2d_18 (Conv2D)              (None, 1, 1, 512)    2359808     zero_padding2d_14[0][0]          
__________________________________________________________________________________________________
batch_normalization_19 (BatchNo (None, 1, 1, 512)    2048        conv2d_18[0][0]                  
__________________________________________________________________________________________________
activation_15 (Activation)      (None, 1, 1, 512)    0           batch_normalization_19[0][0]     
__________________________________________________________________________________________________
zero_padding2d_15 (ZeroPadding2 (None, 3, 3, 512)    0           activation_15[0][0]              
__________________________________________________________________________________________________
conv2d_19 (Conv2D)              (None, 1, 1, 512)    2359808     zero_padding2d_15[0][0]          
__________________________________________________________________________________________________
batch_normalization_20 (BatchNo (None, 1, 1, 512)    2048        conv2d_19[0][0]                  
__________________________________________________________________________________________________
add_7 (Add)                     (None, 1, 1, 512)    0           batch_normalization_20[0][0]     
                                                                 activation_14[0][0]              
__________________________________________________________________________________________________
activation_16 (Activation)      (None, 1, 1, 512)    0           add_7[0][0]                      
__________________________________________________________________________________________________
feature (GlobalAveragePooling2D (None, 512)          0           activation_16[0][0]              
__________________________________________________________________________________________________
dropout (Dropout)               (None, 512)          0           feature[0][0]                    
__________________________________________________________________________________________________
predictions (AMSoftmax)         (None, 40)           20480       dropout[0][0]                    
==================================================================================================
Total params: 11,209,536
Trainable params: 11,199,808
Non-trainable params: 9,728
__________________________________________________________________________________________________
WARNING:tensorflow:From F:/6_Source-code/SmooFaceEngine/train.py:60: Model.fit_generator (from tensorflow.python.keras.engine.training) is deprecated and will be removed in a future version.
Instructions for updating:
Please use Model.fit, which supports generators.
Epoch 1/1000
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3_py35\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-64aafbc7da65>", line 1, in <module>
    runfile('F:/6_Source-code/SmooFaceEngine/train.py', wdir='F:/6_Source-code/SmooFaceEngine')
  File "C:\Program Files\JetBrains\PyCharm 2020.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2020.1\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "F:/6_Source-code/SmooFaceEngine/train.py", line 60, in <module>
    validation_steps=int(validation_set_size) / batch_size)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python35\site-packages\tensorflow\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python35\site-packages\tensorflow\python\keras\engine\training.py", line 1829, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python35\site-packages\tensorflow\python\keras\engine\training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python35\site-packages\tensorflow\python\keras\engine\training.py", line 1098, in fit
    tmp_logs = train_function(iterator)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python35\site-packages\tensorflow\python\eager\def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python35\site-packages\tensorflow\python\eager\def_function.py", line 823, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python35\site-packages\tensorflow\python\eager\def_function.py", line 697, in _initialize
    *args, **kwds))
  File "C:\Users\Administrator\AppData\Roaming\Python\Python35\site-packages\tensorflow\python\eager\function.py", line 2855, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python35\site-packages\tensorflow\python\eager\function.py", line 3213, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python35\site-packages\tensorflow\python\eager\function.py", line 3075, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "C:\Users\Administrator\AppData\Roaming\Python\Python35\site-packages\tensorflow\python\framework\func_graph.py", line 986, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python35\site-packages\tensorflow\python\eager\def_function.py", line 600, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python35\site-packages\tensorflow\python\framework\func_graph.py", line 973, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:
    C:\Users\Administrator\AppData\Roaming\Python\Python35\site-packages\tensorflow\python\keras\engine\training.py:806 train_function  *
        return step_function(self, iterator)
    C:\Users\Administrator\AppData\Roaming\Python\Python35\site-packages\tensorflow\python\keras\engine\training.py:796 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    C:\Users\Administrator\AppData\Roaming\Python\Python35\site-packages\tensorflow\python\distribute\distribute_lib.py:1211 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    C:\Users\Administrator\AppData\Roaming\Python\Python35\site-packages\tensorflow\python\distribute\distribute_lib.py:2585 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    C:\Users\Administrator\AppData\Roaming\Python\Python35\site-packages\tensorflow\python\distribute\distribute_lib.py:2945 _call_for_each_replica
        return fn(*args, **kwargs)
    C:\Users\Administrator\AppData\Roaming\Python\Python35\site-packages\tensorflow\python\keras\engine\training.py:789 run_step  **
        outputs = model.train_step(data)
    C:\Users\Administrator\AppData\Roaming\Python\Python35\site-packages\tensorflow\python\keras\engine\training.py:757 train_step
        self.trainable_variables)
    C:\Users\Administrator\AppData\Roaming\Python\Python35\site-packages\tensorflow\python\keras\engine\training.py:2737 _minimize
        trainable_variables))
    C:\Users\Administrator\AppData\Roaming\Python\Python35\site-packages\tensorflow\python\keras\optimizer_v2\optimizer_v2.py:562 _aggregate_gradients
        filtered_grads_and_vars = _filter_grads(grads_and_vars)
    C:\Users\Administrator\AppData\Roaming\Python\Python35\site-packages\tensorflow\python\keras\optimizer_v2\optimizer_v2.py:1271 _filter_grads
        ([v.name for _, v in grads_and_vars],))
    ValueError: No gradients provided for any variable: ['conv1/kernel:0', 'conv1/bias:0', 'batch_normalization/gamma:0', 'batch_normalization/beta:0', 'conv2d/kernel:0', 'conv2d/bias:0', 'batch_normalization_1/gamma:0', 'batch_normalization_1/beta:0', 'conv2d_1/kernel:0', 'conv2d_1/bias:0', 'conv2d_2/kernel:0', 'conv2d_2/bias:0', 'batch_normalization_2/gamma:0', 'batch_normalization_2/beta:0', 'batch_normalization_3/gamma:0', 'batch_normalization_3/beta:0', 'conv2d_3/kernel:0', 'conv2d_3/bias:0', 'batch_normalization_4/gamma:0', 'batch_normalization_4/beta:0', 'conv2d_4/kernel:0', 'conv2d_4/bias:0', 'batch_normalization_5/gamma:0', 'batch_normalization_5/beta:0', 'conv2d_5/kernel:0', 'conv2d_5/bias:0', 'batch_normalization_6/gamma:0', 'batch_normalization_6/beta:0', 'conv2d_6/kernel:0', 'conv2d_6/bias:0', 'conv2d_7/kernel:0', 'conv2d_7/bias:0', 'batch_normalization_7/gamma:0', 'batch_normalization_7/beta:0', 'batch_normalization_8/gamma:0', 'batch_normalization_8/beta:0', 'conv2d_8/kernel:0', 'conv2d_8/bias:0', 'batch_normalization_9/gamma:0', 'batch_normalization_9/beta:0', 'conv2d_9/kernel:0', 'conv2d_9/bias:0', 'batch_normalization_10/gamma:0', 'batch_normalization_10/beta:0', 'conv2d_10/kernel:0', 'conv2d_10/bias:0', 'batch_normalization_11/gamma:0', 'batch_normalization_11/beta:0', 'conv2d_11/kernel:0', 'conv2d_11/bias:0', 'conv2d_12/kernel:0', 'conv2d_12/bias:0', 'batch_normalization_12/gamma:0', 'batch_normalization_12/beta:0', 'batch_normalization_13/gamma:0', 'batch_normalization_13/beta:0', 'conv2d_13/kernel:0', 'conv2d_13/bias:0', 'batch_normalization_14/gamma:0', 'batch_normalization_14/beta:0', 'conv2d_14/kernel:0', 'conv2d_14/bias:0', 'batch_normalization_15/gamma:0', 'batch_normalization_15/beta:0', 'conv2d_15/kernel:0', 'conv2d_15/bias:0', 'batch_normalization_16/gamma:0', 'batch_normalization_16/beta:0', 'conv2d_16/kernel:0', 'conv2d_16/bias:0', 'conv2d_17/kernel:0', 'conv2d_17/bias:0', 'batch_normalization_17/gamma:0', 'batch_normalization_17/beta:0', 'batch_normalization_18/gamma:0', 'batch_normalization_18/beta:0', 'conv2d_18/kernel:0', 'conv2d_18/bias:0', 'batch_normalization_19/gamma:0', 'batch_normalization_19/beta:0', 'conv2d_19/kernel:0', 'conv2d_19/bias:0', 'batch_normalization_20/gamma:0', 'batch_normalization_20/beta:0', 'predictions/kernel:0'].

**Comment by wotchin** [comment]
这是什么版本的tensorflow？
看样子像是 keras 中的bug.
ref:
https://github.com/tensorflow/tensorflow/issues/1511

**Comment by mixml** [comment]
TensorFlow版本：2.3.0
windows10操作系统

**Comment by wotchin** [comment]
ok, 是tensorflow 版本的问题，这个版本切换到2.0 以下，应该就Ok了。
而且，现在这套代码2.0及以上跑会有一些兼容性问题，相关适配后的代码我还没有上传。

**Comment by mixml** [comment]
好的，谢谢，我切换到旧版本的TensorFlow再试试。

**Comment by wotchin** [comment]
感谢反馈，如果有什么问题还请进一步交流。
