### ISSUE TITLE
Python人脸识别从入门到工程实践章节源码

### ISSUE THREAD

**Issue by nongmo007** [wotchin/SmooFaceEngine#24]
请问作者是否方便提供《Python人脸识别从入门到工程实践》书籍的章节源码

**Comment by wotchin** [comment]
https://github.com/wotchin/SmooFaceEngine/tree/master/chapter-code

**Comment by nongmo007** [comment]
您好，chapter-code中的源码应该只是部分吧，请问有书中所有的示例代码吗？

**Comment by wotchin** [comment]
其他示例代码都在master分支中展示出来了，master分支中的代码是tensorflow2.0 以下版本的代码，另外一个分支是tensorflow 2.0以上版本的代码。

**Comment by JamesRu118** [comment]
我想请教一个代码上的问题，我在运行您的demo时，在预测上出现了一个bug。当运行predict.py做预测时，其中调用了feature = get_feature(img)，将图片作为参数传进去，再间接调用def get_feature_function(model, **kwargs):函数，可是该函数中img = cv2.resize(img, input_shape[:-1])语句需要一个二维的img，但我执行demo时出现以下问题：
File "F:\anaconda\lib\site-packages\utils\feature.py", line 32, in inner
    img = cv2.resize(img, input_shape[:-1])
cv2.error: OpenCV(4.6.0) :-1: error: (-5:Bad argument) in function 'resize'
> Overload resolution failed:
>  - Can't parse 'dsize'. Expected sequence length 2, got 0
>  - Can't parse 'dsize'. Expected sequence length 2, got 0
我理解的是获取到维度为0，因此是没有获取到图片，但实际我去尝试过显示每一张img，都是能获取的，想请教您一下是什么问题。（ps我以为是OpenCV版本的问题，但我换过了4.6.0也不行）

**Comment by wotchin** [comment]
看样子推测，可能是opencv存在大的版本差异，导致`img`加载和`resize` 的行为通过原有代码无法正常衔接。
可以尝试：
1. 将opencv的版本回退到更老的大版本上；
2. debug看下`resize` 函数的输入参数 `img` 是什么内容，在哪一步存在异常值，针对性地适配下。

**Comment by JamesRu118** [comment]
好的好的，我用debug复查一下，感谢您



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Wotchin ***@***.***&gt;
发送时间: 2023年5月4日 10:58
收件人: wotchin/SmooFaceEngine ***@***.***&gt;
抄送: JamesRu118 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [wotchin/SmooFaceEngine] Python人脸识别从入门到工程实践章节源码 (Issue #24)





 
看样子推测，可能是opencv存在大的版本差异，导致img加载和resize 的行为通过原有代码无法正常衔接。
 可以尝试：
  
将opencv的版本回退到更老的大版本上；
 
debug看下resize 函数的输入参数 img 是什么内容，在哪一步存在异常值，针对性地适配下。
