### ISSUE TITLE
勘误

### ISSUE THREAD

**Issue by CWBARSA** [wotchin/SmooFaceEngine#4]
第27页：
“我们注意到，最大化1/||w||2与最小化1/2||w||2是等价的。。。。。。。”
“ 最小化1/(2||w||2) ‘’应该改为 “最小化1/2  ||w||2”

**Comment by wotchin** [comment]
感谢提交issue! 
等我晚上回去看一下后再回复您哈~

**Comment by wotchin** [comment]
好的，已更正，感谢提交
