### ISSUE TITLE
自己实现数据增强代码有误

### ISSUE THREAD

**Issue by duwei0227** [wotchin/SmooFaceEngine#7]
图书133页，代码清单5-3 自己实现简单的数据增强  
do_random_crop 和 do_random_rotation 函数内容一致，但是图书描述是说分别实现随机裁剪与随机旋转

**Comment by wotchin** [comment]
等我把代码修改一下再回复您～

**Comment by wotchin** [comment]
你好，这两个函数代码一样，该函数既可以实现缩放也可以实现裁剪。该函数实现的是仿射变换，裁剪由offset变量决定，缩放由scale_factor决定，这两个变量的值由均匀分布随机数决定。
准确来说，这两个函数应该每一个函数中只随机一个变量，不过原理是没有问题的哈～
