### ISSUE TITLE
获取某一层网络输出结果示例代码有误

### ISSUE THREAD

**Issue by duwei0227** [wotchin/SmooFaceEngine#8]
图书141页，获取LeNet-5全连接层输出结果
* 载入模型路径和训练时定义的模型名称不匹配
*  `get_feature_function`调用时参数名为 `output_layer` 实际为 `output_layer_index`
* `get_fuature_function` 定位输出层时索引使用 `output_layer`
* 没有 `import keras`，后边`load_model`会报错
* 没有 `import numpy as np` 后边 `np.expand_dims`报错

**Comment by wotchin** [comment]
感谢提交！
由于是示范代码，没有注重调试，带来了困扰。
如果后续有时间考虑将示例代码整理到jupyter中，再次感谢。

建议的更正方法：
１) 代码清单５-5:
 将output_layer_index　改为　output_layer

２）下面代码中加入import引入
