### ISSUE TITLE
3.4.2中值滤波

### ISSUE THREAD

**Issue by LinearPi** [wotchin/SmooFaceEngine#9]
图3-8 中指滤波过程演示，图片中 第[1，1]的值应该是2吧

**Comment by wotchin** [comment]
是的，已经在最新版的书中更正啦。
该问题已经刷新到 勘误表中啦，感谢提交~

**Comment by LinearPi** [comment]
恩，在看 github上面的时候看到了。




------------------ 原始邮件 ------------------
发件人: "Wotchin"<notifications@github.com>; 
发送时间: 2019年7月19日(星期五) 上午10:38
收件人: "wotchin/SmooFaceEngine"<SmooFaceEngine@noreply.github.com>; 
抄送: "李杰"<807745654@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [wotchin/SmooFaceEngine] 3.4.2中值滤波 (#9)




是的，已经在最新版的书中更正啦。
 该问题已经刷新到 勘误表中啦，感谢提交~
